### PR TITLE
Allow hector server to be configured from the command line

### PR DESCRIPTION
**Pull request by clintecker**
Allows a server administrator to adjust the address and ports from the command line tool

### CODE REVIEW

**Comment by sstephenson** [comment]
Good idea. I think I'd prefer to use something like `optparse` (positional arguments suck). Another idea would be to read this from a YAML file in the `.hect` directory.

**Comment by clintecker** [comment]
Yea, I was sort of just following the lead of the other CLI tools. I was also wondering last night if it would be something you could just configure on the server level (like the yaml file) or inside the init.rb (like how the server name is set).

**Comment by sstephenson** [comment]
Yeah, init.rb sounds like the easiest way to make this work.

**Comment by clintecker** [comment]
Applied at sstephenson@a830a2ab31b9942b3475 and documented at sstephenson@002b5925556b54533dd9

**Pull request closed without merging**
